### ISSUE TITLE
following s3 path access denied

### ISSUE THREAD

**Issue by bitedd** [aws-samples/aws-ai-ml-workshop-kr#93]
* s3 path
  + https://ee-assets-prod-us-east-1.s3.us-east-1.amazonaws.com/modules/c16b965656fb4eba8676d6f0ac759300/v1/ncf/MLOps-CF.yaml

<img width="1414" alt="image" src="https://github.com/aws-samples/aws-ai-ml-workshop-kr/assets/40716479/f87d261d-9a1a-40b6-896d-4a3c1fb0dbf4">

**Comment by bitedd** [comment]
Could you fix s3 path information?

**Comment by gonsoomoon-ml** [comment]
I have fixed the issue replacing the old s3 path with new s3 path.

**Comment by hahabattery** [comment]
Thank you for your your work. It is very helpful!
